server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://${LOCAL_HOST}:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_ADDRESS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.example.ecommerce.notification.dto.PaymentNotificationRequest

application:
  config:
    product-url: ${PRODUCT_URL}