name: Cart Service CI/CD Pipeline

on:
  push:
    paths:
      - 'services/cart-service/**'
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./services/cart-service

      - name: Test with Maven
        run: mvn test
        working-directory: ./services/cart-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: docker build -t dungpham2502/cart-service:latest ./services/cart-service

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./services/cart-service
          push: true
          tags: dungpham2502/cart-service:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          timeout: 60m
          command_timeout: 30m
          script: |
            docker pull dungpham2502/cart-service:latest

            docker stop cart-service || true
            docker rm cart-service || true

            docker run -d -p 8100:8100 --name cart-service dungpham2502/cart-service:latest
