name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment
    strategy:
      matrix:  # Define a matrix to run the job for each service
        service: [eureka-config-server, eureka-discovery-server, api-gateway-server, customer-service, product-service, cart-service, order-service, payment-service, notification-service]

    steps:
      - name: Checkout code  # Step to check out the repository code
        uses: actions/checkout@v2

      - name: Set up JDK 17  # Step to set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages  # Step to cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven  # Step to build the project using Maven
        run: mvn clean install -DskipTests
        working-directory: ./services/${{ matrix.service }}

      - name: Test with Maven  # Step to run tests using Maven
        run: mvn test
        working-directory: ./services/${{ matrix.service }}

      - name: Login to Docker Hub  # Step to log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image  # Step to build the Docker image
        run: docker build -t dungpham2502/${{ matrix.service }}:latest ./services/${{ matrix.service }}

      - name: Push Docker image to Docker Hub  # Step to push the Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: dungpham2502/${{ matrix.service }}:latest

  deploy:
    needs: build_and_push  # Run this job only if build_and_push job succeeds
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      - name: Checkout code  # Step to check out the repository code
        uses: actions/checkout@v2

      - name: Login to Docker Hub  # Step to log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to server  # Step to deploy the services to the server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            services=(eureka-config-server eureka-discovery-server api-gateway-server customer-service product-service cart-service order-service payment-service notification-service)
            for service in "${services[@]}"; do
              docker pull dungpham2502/$service:latest

              docker stop $service || true
              docker rm $service || true

              case $service in
                eureka-config-server)
                  port=8888
                  ;;
                eureka-discovery-server)
                  port=8761
                  ;;
                api-gateway-server)
                  port=8222
                  ;;
                customer-service)
                  port=8090
                  ;;
                product-service)
                  port=8050
                  ;;
                cart-service)
                  port=8100
                  ;;
                order-service)
                  port=8070
                  ;;
                payment-service)
                  port=8060
                  ;;
                notification-service)
                  port=8040
                  ;;
                *)
                  port=8000
                  ;;
              esac

              docker run -d -p $port:8080 --name $service dungpham2502/$service:latest
            done
